export enum Page {
    HOME_PAGE = 'HOME_PAGE',
    OFFER = 'OFFER',
    COMPANY = 'COMPANY',
    LOGIN = 'LOGIN',
    SIGN_IN = 'SIGN_IN',
    DECONNECTION = 'DECONNECTION',
    PROFILE = 'PROFILE',
    USER_SETTINGS = 'USER_SETTINGS'
}



